<div class="container " style="flex: 1;">
	<div class="row mt-3">
		<div class="col d-flex justify-content-center">
			<img src="/img/logo.svg" class="img-fluid width-img">
		</div>
	</div>

	<div class="row mt-5 ">
		<div class="col d-flex justify-content-center ">
			<div class="conteudo-caixa">

				<form method="post" action="/logar">
					<input class="form-control mb-3" type="text" name="email" placeholder="EMAIL">
					<input class="form-control mb-3" type="password" name="senha" placeholder="SENHA">
					
					<div class="d-flex justify-content-center">
						<button type="submit" class="btn btn-costum btn-blue">Entrar</button>
						<a href="/cadastro" class="btn btn-yellow ml-auto">Registrar</a>
					</div>
				</form>	

				<?php if($this->view->login == 'erro') {  ?>
					<div class="text text-danger mt-3">Email e/ou senha inválido(s)!</div>
				<?php } ?>

			</div>
		</div>
	</div>
</div>