<!DOCTYPE html>
	<head>
		<title>Calcula Conta</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<link rel="stylesheet" type="text/css" href="/css/media-querie.css">

	</head>

	<body>	

		<header>

			<nav class="navbar navbar-expand-lg">

				<div class="container">
					<!-- Logo -->
					<img src="/img/logo.svg" class="img-fluid">

					<!--- menu hamburger -->
					<button class="navbar-toggler" data-toggle="collapse" data-target="#nav-target">
					    <img src="/img/menu_hamb.svg">
					</button>

					<!--- navegação -->
		        	<div id="nav-target"class="collapse navbar-collapse">

						<ul class="navbar-nav ml-auto">
							<li class="nav-item">
								<a class="nav-link" href="/timeline">Home</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="/nova_divida">Nova Dívida</a>
							</li>

							<li class="nav-item dropdown">
								
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          						Listar por 
          						</a>

          						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          							<h6 class="dropdown-header"><strong>Ano</strong></h6>
          							<form method="GET" action="/pesquisar">
          								<input type="number" name="ano" class="form-control" value="<?=$this->view->anoAtual?>" required>
          								<input type="hidden" name="por" value="ano">
          								<button type="submit" class="btn btn-warning btn-block">Listar</button>
          							</form>

          							<h6 class="dropdown-header"><strong>Categoria</strong></h6>
          							<form method="GET" action="/pesquisar">
          								<select name="categoria" required class="form-control">
                							<?php foreach ($this->view->categorias as $key => $categoria) { ?>
                								<option value="<?= $categoria['id'] ?>"><?= $categoria['descricao'] ?></option>
                							<?php } ?>                							
            							</select>

          								<input type="month" name="mesAno" class="form-control" required>
          								<input type="hidden" name="por" value="categoria">
          								<button type="submit" class="btn btn-warning btn-block">Listar</button>
          							</form>
        						</div>
						          
							</li>

							<li class="nav-item">
								<a class="nav-link" href="/sobre">Sobre o Aplicativo</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="/sair">Sair</a>
							</li>
						</ul>

					</div>
				</div>

			</nav>

		</header>	
	

		<?= $this->content() ?>

		<footer>
			<div class="container">
				Copyright © 2021 | <a href="http://tanisemoura.epizy.com/">Tanise Moura</a>
			</div>
		</footer>


	</body>
</html>