<section style="flex: 1;" class="mt-3 mb-3">

	<div class="container">
		<div class="row d-flex justify-content-center">
			
			<div class="col-md-8 caixa-titulo bg-dark">
				<h3 class="titulo">Alteração de Dívida</h3>
			</div>

			<div class="col-md-8 mt-3">
				<form method="post" action="/altCadDivida?acao=alterar">
					<div class="input-group d-flex justify-content-center">
			           <div class="input-group-prepend">
			               <h1 class="form-valor-simb">R$</h1>
			           </div>
			           <input class="form-valor" name="valor" type="number" step="any" placeholder=",00" min="0" required value="<?=$this->view->divida_alterar['valor']?>">
			           
       				</div> 

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Descrição</span>
			           </div>
           				<input class="form-control form-cadastro" name="descricao" type="text" value="<?=$this->view->divida_alterar['descricao']?>">
       				</div> 

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Data</span>
			           </div>
           				<input class="form-control form-cadastro" name="data" type="date" value="<?=$this->view->divida_alterar['data']?>" required>
       				</div>

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Categoria</span>
			           </div>
           				<select name="categoria" required class="form-control form-cadastro">
                			<?php foreach ($this->view->categorias as $key => $categoria) { ?>
                				<option <?= $this->view->divida_alterar['categoria'] == $categoria['id'] ? 'selected' : '' ?> value="<?= $categoria['id'] ?>"><?= $categoria['descricao'] ?></option>
                			<?php } ?>
            			</select>
       				</div>

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Repetir?</span>
			           </div>

           				<input class="form-control form-cadastro" name="repetir" type="number" min="0" value="0">

           				<input type="hidden" name="id" value="<?=$this->view->divida_alterar['id']?>">
           				<?php if (!isset($_GET['por'])) { ?>
           					<input type="hidden" name="ano" value="<?=$_GET['ano']?>">
           					<input type="hidden" name="mes" value="<?=$_GET['mes']?>">
           				<?php }?>
           				<input type="hidden" name="pagina" value="<?=$_GET['pagina']?>">

           				<?php if (isset($_GET['por']) && $_GET['por'] == 'categoria') { ?>
           					<input type="hidden" name="por" value="<?=$_GET['por']?>">
           					<input type="hidden" name="categoria" value="<?=$_GET['categoria']?>">
           					<input type="hidden" name="mesAno" value="<?=$_GET['mesAno']?>">
           				<?php }?>

           				<?php if (isset($_GET['por']) && $_GET['por'] == 'ano') { ?>
           					<input type="hidden" name="ano" value="<?=$_GET['ano']?>">
           					<input type="hidden" name="por" value="<?=$_GET['por']?>">
           				<?php }?>

       				</div>

					<div class="d-flex justify-content-center mt-3">
						<button type="submit" class="btn btn-costum btn-blue">Alterar</button>
					</div>


				</form>
			</div>

		</div>
	</div>

</section>