<?php if(isset($_GET['sucesso']) ? $_GET['sucesso'] : false) {?>
	<div class="alert alert-success text-center alert-dismissible fade show" role="alert">
	 Dívida cadastrada com sucesso!
	 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
  	</button>
	</div>
<?php } ?>

<section style="flex: 1;" class="mt-3 mb-3">

	<div class="container">
		<div class="row d-flex justify-content-center">
			
			<div class="col-md-8 caixa-titulo bg-dark">
				<h3 class="titulo">Cadastro de Dívida</h3>
			</div>

			<div class="col-md-8 mt-3">
				<form method="post" action="/altCadDivida?acao=salvar">
					<div class="input-group d-flex justify-content-center">
			           <div class="input-group-prepend">
			               <h1 class="form-valor-simb">R$</h1>
			           </div>
			           <input class="form-valor" name="valor" type="number" step="any" placeholder=",00" min="0" required>
			           
       				</div> 

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Descrição</span>
			           </div>
           				<input class="form-control form-cadastro" name="descricao" type="text">
       				</div> 

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Data</span>
			           </div>
           				<input class="form-control form-cadastro" name="data" type="date" required>
       				</div>

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Categoria</span>
			           </div>
           				<select name="categoria" required class="form-control form-cadastro">

                			<?php foreach ($this->view->categorias as $key => $categoria) { ?>
                				<option value="<?= $categoria['id'] ?>"><?= $categoria['descricao'] ?></option>
                			<?php } ?>

            			</select>

       				</div>

       				<div class="input-group mt-3">
			           <div class="input-group-prepend">
			               <span class="input-group-text">Repetir?</span>
			           </div>

           				<input class="form-control form-cadastro" name="repetir" type="number" min="0" value="0">

       				</div>

					<div class="d-flex justify-content-center mt-3">
						<button type="submit" class="btn btn-costum btn-blue">Cadastrar</button>
					</div>


				</form>
			</div>

		</div>
	</div>

</section>