<section style="flex: 1;">
	<div class="container mb-3 mt-3">
		<div class="row d-flex justify-content-center">
			<div class="col-md-6">
				
				<div class="card">
					
					<div class="card-header bg-dark">
						<h3 class="text-center titulo">Sobre o Aplicativo</h3>
					</div>

					<div class="card-body">
						<p>Esse aplicativo foi criado com o intuito de estudar e revisar conceitos
						vistos durante o curso de Desenvolvimento Web, principalmente a parte da estrutura MVC.</p>

						<p>O objetivo do aplicativo é possibilitar o cadastro de contas para pagar, podendo lista-las por mês ou por categorias que podem ser cadastradas pelo próprio usuário.</p>

						<p>Com o sistema de login cada usuário terá suas informações guardadas em um banco de dadose será exibido somente os dados do usuário logado.</p>

						<p>Abaixo segue os links de créditos aos autores dos ícones que usei nesse projeto:</p>

						<div><a href="https://www.flaticon.com/authors/freepik" title="Freepik">
							<strong>Freepik</strong></a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

						<div><a href="https://www.flaticon.com/authors/kiranshastry" title="Kiranshastry"><strong>Kiranshastry</strong></a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

						<div><a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect"><strong>Pixel perfect</strong></a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>


					</div>


				</div>

			</div>
		</div>
	</div>
</section>